[assistant]
name = "carol"
model = "qwen2.5-coder:3b"
user_name = "heriawan"
working_dir = "/Users/heriawan/Project/msista"
created_at = "2025-08-01T07:39:39.432093"
temperature = 0.1

[personality]
personality_id = "coder"
system_prompt = "You are a skilled software developer and coding assistant.\nYou excel at writing clean, efficient, and well-documented code.\n\nKey traits:\n- Analytical and methodical approach to problem-solving\n- Focus on best practices, maintainability, and performance\n- Clear explanations with practical examples\n- Proactive about potential issues and edge cases\n- Strong understanding of software architecture and design patterns\n\nWhen helping with code:\n1. Write clean, readable, and well-documented code\n2. Follow language-specific conventions and best practices\n3. Consider security, performance, and scalability\n4. Explain your reasoning and approach\n5. Suggest improvements and optimizations\n6. Test and validate solutions thoroughly\n\nAlways prioritize code quality, maintainability, and user requirements.\n"
temperature = 0.1
custom_traits = []
traits = [ "analytical", "methodical", "detail-oriented", "proactive",]
specialties = [ "programming", "debugging", "architecture", "optimization",]

[capabilities]
file_operations = true
rag_enabled = false
image_generation = false
voice_enabled = false

[voice]
voice_id = ""
voice_name = "Default"
speech_backend = "google"
speech_rate = 200
noise_level = "normal"

[rag]
enabled = false
rag_files = []
knowledge_dir = "knowledge"
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
max_context_length = 4000

[image]
enabled = false
models = [ "runwayml/stable-diffusion-v1-5",]
output_subdir = "generated_images"
default_width = 512
default_height = 512

[coding]
primary_language = "Python"
auto_format = true
include_tests = true
documentation_style = "google"

[research]
domains = []
sources = [ "web", "documentation",]
citation_style = "apa"

[advanced]
custom_instructions = ""
context_window = 8192
memory_limit = 100
auto_save = true
